In [1]:
from quantum_annealing_portfolio_optimization import *

In [2]:
si = StockInfo(num_stocks=20)

In [3]:
si.names

{'005930': '삼성전자',
 '000660': 'SK하이닉스',
 '034020': '두산에너빌리티',
 '042660': '한화오션',
 '035420': 'NAVER',
 '006400': '삼성SDI',
 '108490': '로보티즈',
 '005380': '현대차',
 '005935': '삼성전자우',
 '086520': '에코프로',
 '042700': '한미반도체',
 '373220': 'LG에너지솔루션',
 '035720': '카카오',
 '010140': '삼성중공업',
 '196170': '알테오젠',
 '090360': '로보스타',
 '247540': '에코프로비엠',
 '012450': '한화에어로스페이스',
 '466100': '클로봇',
 '051910': 'LG화학'}

In [4]:
si.tickers

['005930',
 '000660',
 '034020',
 '042660',
 '035420',
 '006400',
 '108490',
 '005380',
 '005935',
 '086520',
 '042700',
 '373220',
 '035720',
 '010140',
 '196170',
 '090360',
 '247540',
 '012450',
 '466100',
 '051910']

In [5]:
si.last_prices

array([ 97900., 580000.,  77900., 126800., 260000., 306000., 221000.,
       264000.,  75300.,  87200., 127200., 463500.,  62800.,  26300.,
       528000.,  77200., 151100., 923000.,  37150., 382000.])

In [6]:
si.df_returns

,005930,000660,034020,042660,035420,006400,108490,005380,005935,086520,042700,373220,035720,010140,196170,090360,247540,012450,466100,051910
date,,,,,,,,,,,,,,,,,,,,
2024-11-11,-3.508772,-3.940150,-2.564103,3.038674,0.801833,-3.514831,-2.214379,3.685504,-2.542373,-3.768777,-6.475584,4.391468,-3.714286,7.356948,1.945080,-3.211009,-4.919054,3.097944,12.377451,0.330033
2024-11-12,-3.636364,-3.530633,-0.239234,-1.340483,3.068182,-3.642872,-1.926883,-1.895735,-2.717391,0.782477,-3.859251,2.644231,-1.335312,-2.030457,-1.346801,-4.739336,0.130976,-0.601020,-1.526718,0.493421
2024-11-13,-4.528302,-1.560818,-0.479616,-8.152174,0.441014,-3.402921,-2.314952,-3.429952,-4.692737,-3.496448,-3.069658,-3.512881,0.451128,-3.022453,-4.095563,-0.497512,-5.624591,-2.781114,-0.996678,-5.400982
2024-11-14,-1.383399,-5.412794,8.192771,15.976331,3.457739,3.522799,-1.774321,0.800400,0.703400,-7.919437,-1.218027,2.427184,-1.796407,4.363313,4.744958,-2.500000,-6.375606,0.373120,-9.843400,-0.519031
2024-11-15,7.214429,3.005780,-2.672606,-0.255102,0.795756,-6.805456,3.192082,2.233251,6.868452,-4.811436,0.739827,-12.085308,3.810976,1.450512,-0.906002,4.871795,-7.846040,0.867545,1.240695,-3.304348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-11-03,3.348837,10.912343,0.901917,0.872093,2.616822,1.552795,24.489796,0.517241,2.843602,7.727273,-1.461378,0.528541,-0.921659,-2.030457,7.062436,17.031070,3.062500,6.435138,14.778325,-1.132075
2025-11-04,-5.580558,-5.483871,0.000000,-1.585014,-2.732240,3.211009,-2.003643,-5.317324,-5.529954,0.949367,-1.341808,-0.525762,-0.465116,-0.863558,4.971319,-5.899705,-1.879927,-3.071017,-1.716738,0.508906
2025-11-05,-4.099142,-1.194539,-6.592179,-7.467057,4.307116,-3.703704,-9.851301,-2.717391,-4.878049,-3.030303,-4.724409,-1.902748,-2.336449,-4.355401,-3.642987,-7.105538,-2.410383,-5.940594,-8.951965,-2.531646
2025-11-06,-1.391650,2.417962,-5.143541,-2.689873,-5.206463,-0.923077,-10.927835,0.186220,-1.538462,0.431034,-3.080391,1.293103,-3.189793,-4.735883,3.402647,-9.786277,0.063331,2.105263,-9.112710,0.129870
2025-11-07,-1.310484,-2.192243,-1.765448,3.089431,-1.515152,-4.968944,2.314815,-1.858736,-1.953125,-6.437768,-1.395349,-1.382979,3.459638,0.573614,-3.473492,-3.740648,-4.367089,-4.845361,-1.978892,-0.907912

In [7]:
si.tickers

['005930',
 '000660',
 '034020',
 '042660',
 '035420',
 '006400',
 '108490',
 '005380',
 '005935',
 '086520',
 '042700',
 '373220',
 '035720',
 '010140',
 '196170',
 '090360',
 '247540',
 '012450',
 '466100',
 '051910']

In [8]:
si.average_returns

[0.24730433299414611,
 0.4956629074223969,
 0.6154381464345896,
 0.6060820381623802,
 0.20084151855801094,
 0.08655172551436839,
 1.2455045307030053,
 0.1316389618700262,
 0.21433663404722858,
 0.12434931783767549,
 0.20323984447621746,
 0.11060175049773233,
 0.296527174071093,
 0.40935952279796955,
 0.15332299699081572,
 0.6347855697441454,
 0.04985207572838831,
 0.43387327690982624,
 0.7817828939348448,
 0.14181482321202069]

In [9]:
si.df_covariances

,005930,000660,034020,042660,035420,006400,108490,005380,005935,086520,042700,373220,035720,010140,196170,090360,247540,012450,466100,051910
005930,4.576642,3.403025,1.663153,0.916103,0.999963,2.576639,2.050333,2.106653,4.034454,3.029866,3.702600,1.623011,1.285737,1.129197,1.503989,2.629385,2.652135,0.436740,2.289254,2.457728
000660,3.403025,10.911747,4.441295,0.683168,1.487750,3.019032,5.438339,2.046854,3.075634,4.384120,7.337943,2.440822,2.163579,2.070816,2.467381,5.078579,4.481197,1.534054,5.051529,2.612811
034020,1.663153,4.441295,16.087919,3.212522,2.689708,1.650514,9.094509,0.930386,1.793380,0.394948,6.001197,0.299623,1.732264,3.369386,2.560856,5.883490,0.934183,4.096822,4.971149,0.669213
042660,0.916103,0.683168,3.212522,17.309513,0.046514,-0.267651,2.810630,0.523827,1.161413,-0.311834,2.102280,0.163249,-0.690276,6.152814,3.195226,1.034319,-0.153341,8.919181,0.559749,0.532094
035420,0.999963,1.487750,2.689708,0.046514,7.306463,1.109276,3.791256,1.039548,0.815888,1.313582,1.096165,0.435967,4.130009,0.806645,0.816054,1.926663,1.183799,-0.278248,2.633527,0.844567
006400,2.576639,3.019032,1.650514,-0.267651,1.109276,9.674449,-0.132167,2.555104,2.474187,8.238451,3.421009,6.492309,1.593214,1.066458,0.992565,3.026175,8.781266,-0.416509,0.978788,6.607738
108490,2.050333,5.438339,9.094509,2.810630,3.791256,-0.132167,40.754028,-1.038850,2.003121,-0.434485,5.961296,-1.737523,1.229296,3.020518,3.619951,18.641146,0.406263,4.392407,15.822868,-1.066553
005380,2.106653,2.046854,0.930386,0.523827,1.039548,2.555104,-1.038850,4.782652,2.000987,2.728747,1.916975,2.002450,1.533763,0.967949,0.927146,1.017091,2.710315,-0.022047,0.926763,2.589121
005935,4.034454,3.075634,1.793380,1.161413,0.815888,2.474187,2.003121,2.000987,4.098872,2.753239,3.537168,1.455772,1.079286,1.481952,1.428654,2.591744,2.557828,0.945386,2.313146,2.354255
086520,3.029866,4.384120,0.394948,-0.311834,1.313582,8.238451,-0.434485,2.728747,2.753239,16.451347,3.596572,7.046484,1.534515,1.491430,1.810684,3.123670,12.882520,-0.890392,1.509575,8.005679
042700,3.702600,7.337943,6.001197,2.102280,1.096165,3.421009,5.961296,1.916975,3.537168,3.596572,16.214662,2.008464,1.542597,2.843165,1.095441,5.241385,4.576441,2.082255,4.782725,2.905835
373220,1.623011,2.440822,0.299623,0.163249,0.435967,6.492309,-1.737523,2.002450,1.455772,7.046484,2.008464,9.721675,0.453828,0.834229,1.238848,1.776429,8.060395,0.112498,-0.222936,6.011143
035720,1.285737,2.163579,1.732264,-0.690276,4.130009,1.593214,1.229296,1.533763,1.079286,1.534515,1.542597,0.453828,11.033203,1.333375,1.328809,1.453844,1.173424,-0.211294,2.406741,0.921051
010140,1.129197,2.070816,3.369386,6.152814,0.806645,1.066458,3.020518,0.967949,1.481952,1.491430,2.843165,0.834229,1.333375,9.748056,2.553851,1.712451,0.931840,4.461365,2.693022,1.332281
196170,1.503989,2.467381,2.560856,3.195226,0.816054,0.992565,3.619951,0.927146,1.428654,1.810684,1.095441,1.238848,1.328809,2.553851,15.035564,2.386734,1.171698,4.708232,3.889591,1.309931
090360,2.629385,5.078579,5.883490,1.034319,1.926663,3.026175,18.641146,1.017091,2.591744,3.123670,5.241385,1.776429,1.453844,1.712451,2.386734,23.591240,3.159033,2.267313,12.695054,2.194846
247540,2.652135,4.481197,0.934183,-0.153341,1.183799,8.781266,0.406263,2.710315,2.557828,12.882520,4.576441,8.060395,1.173424,0.931840,1.171698,3.159033,15.318351,-0.076788,1.240785,7.475022
012450,0.436740,1.534054,4.096822,8.919181,-0.278248,-0.416509,4.392407,-0.022047,0.945386,-0.890392,2.082255,0.112498,-0.211294,4.461365,4.708232,2.267313,-0.076788,17.103215,2.715206,0.670221
466100,2.289254,5.051529,4.971149,0.559749,2.633527,0.978788,15.822868,0.926763,2.313146,1.509575,4.782725,-0.222936,2.406741,2.693022,3.889591,12.695054,1.240785,2.715206,32.404093,1.680631
051910,2.457728,2.612811,0.669213,0.532094,0.844567,6.607738,-1.066553,2.589121,2.354255,8.005679,2.905835,6.011143,0.921051,1.332281,1.309931,2.194846,7.475022,0.670221,1.680631,9.279534

In [10]:
si.mapping_prices

{'005930': 97900.0,
 '000660': 580000.0,
 '034020': 77900.0,
 '042660': 126800.0,
 '035420': 260000.0,
 '006400': 306000.0,
 '108490': 221000.0,
 '005380': 264000.0,
 '005935': 75300.0,
 '086520': 87200.0,
 '042700': 127200.0,
 '373220': 463500.0,
 '035720': 62800.0,
 '010140': 26300.0,
 '196170': 528000.0,
 '090360': 77200.0,
 '247540': 151100.0,
 '012450': 923000.0,
 '466100': 37150.0,
 '051910': 382000.0}

In [13]:
opt = PortfolioOptimizer(stock_info=si, num_stocks_to_buy=2, budget=1e6)

In [14]:
opt.last_prices

array([500000., 500000., 500000., 500000., 500000., 500000., 500000.,
       500000., 500000., 500000., 500000., 500000., 500000., 500000.,
       500000., 500000., 500000., 500000., 500000., 500000.])

In [15]:
cqm = opt.cqm
cqm

In [16]:
cqm.constraint_labels

Variables(['choose stocks: 2', 'budget limitation: 1000000.0'])

In [17]:
sampleset = opt.sampleset
sampleset

SolverFailureError: Problem not accepted because user has insufficient remaining solver access time in project ZMtm

In [16]:
opt.df_record

| Saved csv to data/dataset-result/dataset-result-record-budget1000000.0-n5-save2025-11-10 10:37:26.csv

,005930,000660,034020,042660,035420,006400,108490,005380,005935,086520,...,090360,247540,012450,466100,051910,energy,num_occurrences,constraints,feasible,total_cost
sample,,,,,,,,,,,,,,,,,,,,,
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.841203,1,"[False, True]",False,744350.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,2.860039,1,"[True, True]",True,908750.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,2.860039,1,"[True, True]",True,908750.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,2.860039,1,"[True, True]",True,908750.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,2.860039,1,"[True, True]",True,908750.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,2.860039,1,"[True, True]",True,908750.0
97,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,2.860039,1,"[True, True]",True,908750.0
98,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,2.860039,1,"[True, True]",True,908750.0
99,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,2.860039,1,"[True, True]",True,908750.0
100,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,2.860039,1,"[True, True]",True,908750.0

In [17]:
opt.df_aggregated_record

| Saved csv to data/dataset-result/dataset-result-aggregate-budget1000000.0-n5-save2025-11-10 10:37:29.csv

,005930,000660,034020,042660,035420,006400,108490,005380,005935,086520,...,090360,247540,012450,466100,051910,energy,num_occurrences,constraints,feasible,total_cost
sample,,,,,,,,,,,,,,,,,,,,,
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.841203,1,"[False, True]",False,744350.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,2.860039,100,"[True, True]",True,908750.0

In [18]:
opt.show_solution()

Solution:

Best feasible solution found:
한화오션 (042660)
로보티즈 (108490)
현대차 (005380)
LG에너지솔루션 (373220)
카카오 (035720)
Energy: 2.8600392263998433

In [6]:
opt = PortfolioOptimizer(stock_info=si, num_stocks_to_buy=3, budget=200)

In [11]:
opt.cqm.constraint_labels

Variables(['choose k stocks', 'budget_limitation'])

In [29]:
mapping_prices = {ticker: float(price) for ticker, price in zip(si.tickers, si.last_prices)}
mapping_prices

{'T': 27.286,
 'SFL': 5.9513,
 'PFE': 35.735,
 'XOM': 39.354,
 'MO': 38.893,
 'VZ': 56.873,
 'IBM': 121.45,
 'TSLA': 705.67,
 'GILD': 56.44,
 'GE': 86.272}

In [17]:
opt = PortfolioOptimizer(stock_info=si, num_stocks_to_buy=2, budget=40)
opt

In [18]:
cqm = opt.cqm
cqm

In [19]:
cqm

In [21]:
opt.sampleset

SampleSet(rec.array([([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], -0.00116939, 1, [ True, False], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], -0.00116939, 1, [ True, False], False),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False)],
          dtype=[('sample', '<f8', (10,)), ('energy', '<f8'), ('num_occurrences', '<i8'), ('is_satisfied', '?', (2,)), ('is_feasible', '?')]), Variables(['stock_GE', 'stock_GILD', 'stock_IBM', 'stock_MO', 'stock_PFE', 'stock_SFL', 'stock_T', 'stock_TSLA', 'stock_VZ', 'stock_XOM']), {'constraint_labels': ['budget_limitation', 'choose k stocks'], 'qpu_access_time': 69450, 'charge_time': 10000000, 'run_time': 10359078, 'problem_id': '9eff6916-7a3d-4efa-bd9c-1e5c08973dbc', 'problem_data_id': '08e4d274-ef55-4a06-90fa-1b31dbab6633'}, 'INTEGER')

In [22]:
opt.process_sampleset()

Solution:

Best feasible solution found:
T
SFL
Energy: -0.001258040134328231

In [23]:
opt.aggregated_record

rec.array([([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 112, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], -0.00116939,   2, [ True, False], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655,   9, [False,  True], False)],
          dtype=[('sample', '<f8', (10,)), ('energy', '<f8'), ('num_occurrences', '<i8'), ('is_satisfied', '?', (2,)), ('is_feasible', '?')])

In [24]:
opt.df_aggregated_record

,T,SFL,PFE,XOM,MO,VZ,IBM,TSLA,GILD,GE,energy,num_occurrences,constraints,feasible
0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,-0.001258,112,"[True, True]",True
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-0.001169,2,"[True, False]",False
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.001767,9,"[False, True]",False

In [32]:
opt.budget

40.0

In [31]:
howmuch = opt.df_aggregated_record[opt.tickers]

def get_total_cost(row):
    total_cost = 0
    for ticker, price in mapping_prices.items():
        total_cost += row[ticker] * price
    return total_cost

howmuch['total_cost'] = howmuch.apply(get_total_cost, axis=1)
howmuch

/var/folders/_1/0byqfsn56tzdr_b7z00g95xw0000gn/T/ipykernel_23307/3831947825.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  howmuch['total_cost'] = howmuch.apply(get_total_cost, axis=1)

     T  SFL  PFE  XOM   MO   VZ  IBM  TSLA  GILD   GE  total_cost
0  0.0  0.0  0.0  0.0  0.0  1.0  1.0   0.0   0.0  0.0     178.323
1  0.0  0.0  0.0  0.0  0.0  1.0  0.0   0.0   0.0  0.0      56.873
2  0.0  0.0  0.0  0.0  0.0  1.0  0.0   0.0   0.0  1.0     143.145

In [ ]:
sampleset = opt.sampleset

<bound method SampleSet.data of SampleSet(rec.array([([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], -0.00116939, 1, [ True, False], False),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], -0.00116939, 1, [ True, False], False)],
          dtype=[('sample', '<f8', (10,)), ('energy', '<f8'), ('num_occurrences', '<i8'), ('is_satisfied', '?', (2,)), ('is_feasible', '?')]), Variables(['stock_GE', 'stock_GILD', 'stock_IBM', 'stock_MO', 'stock_PFE', 'stock_SFL', 'stock_T', 'stock_TSLA', 'stock_VZ', 'stock_XOM']), {'constraint_labels': ['budget_limitation', 'choose k stocks'], 'qpu_access_time': 69447, 'charge_time': 5000000, 'run_time': 5204678, 'problem_id': '6d3cfa40-26d2-41b1-b2b0-460228220e01', 'problem_data_id': '873bfcc8-1b54-4b6e-a8ca-76a4360067a4'}, 'INTEGER')>

In [36]:
sampleset.first

Sample(sample={'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)}, energy=np.float64(-0.0017665541178559215), num_occurrences=np.int64(1), is_satisfied=array([False,  True]), is_feasible=np.False_)

In [34]:
sampleset.first.sample

{'stock_GE': np.float64(0.0),
 'stock_GILD': np.float64(0.0),
 'stock_IBM': np.float64(0.0),
 'stock_MO': np.float64(0.0),
 'stock_PFE': np.float64(0.0),
 'stock_SFL': np.float64(1.0),
 'stock_T': np.float64(0.0),
 'stock_TSLA': np.float64(0.0),
 'stock_VZ': np.float64(0.0),
 'stock_XOM': np.float64(1.0)}

In [37]:
sampleset.first.energy

np.float64(-0.0017665541178559215)

In [38]:
sampleset.first.num_occurrences

np.int64(1)

In [39]:
sampleset.first.is_feasible

np.False_

In [40]:
sampleset.first.is_satisfied

array([False,  True])

In [42]:
sampleset.variables

Variables(['stock_GE', 'stock_GILD', 'stock_IBM', 'stock_MO', 'stock_PFE', 'stock_SFL', 'stock_T', 'stock_TSLA', 'stock_VZ', 'stock_XOM'])

In [43]:
sampleset.info

{'constraint_labels': ['budget_limitation', 'choose k stocks'],
 'qpu_access_time': 69447,
 'charge_time': 5000000,
 'run_time': 5204678,
 'problem_id': '6d3cfa40-26d2-41b1-b2b0-460228220e01',
 'problem_data_id': '873bfcc8-1b54-4b6e-a8ca-76a4360067a4'}

In [44]:
sampleset.record

rec.array([([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], -0.00116939, 1, [ True, False], False),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], -0.00116939, 1, [ True, False], False)],
          dtype=[('sample', '<f8', (10,)), ('energy', '<f8'), ('num_occurrences', '<i8'), ('is_satisfied', '?', (2,)), ('is_feasible', '?')])

In [48]:
sampleset.lowest()

SampleSet(rec.array([([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False)],
          dtype=[('sample', '<f8', (10,)), ('energy', '<f8'), ('num_occurrences', '<i8'), ('is_satisfied', '?', (2,)), ('is_feasible', '?')]), Variables(['stock_GE', 'stock_GILD', 'stock_IBM', 'stock_MO', 'stock_PFE', 'stock_SFL', 'stock_T', 'stock_TSLA', 'stock_VZ', 'stock_XOM']), {'constraint_labels': ['budget_limitation', 'choose k stocks'], 'qpu_access_time': 69447, 'charge_time': 5000000, 'run_time': 5204678, 'problem_id': '6d3cfa40-26d2-41b1-b2b0-460228220e01', 'problem_data_id': '873bfcc8-1b54-4b6e-a8ca-76a4360067a4'}, 'INTEGER')

In [49]:
sampleset.filter(lambda s: s.is_feasible)

SampleSet(rec.array([([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True)],
          dtype=[('sample', '<f8', (10,)), ('energy', '<f8'), ('num_occurrences', '<i8'), ('is_satisfied', '?', (2,)), ('is_feasible', '?')]), Variables(['stock_GE', 'stock_GILD', 'stock_IBM', 'stock_MO', 'stock_PFE', 'stock_SFL', 'stock_T', 'stock_TSLA', 'stock_VZ', 'stock_XOM']), {'constraint_labels': ['budget_limitation', 'choose k stocks'], 'qpu_access_time': 69447, 'charge_time': 5000000, 'run_time': 5204678, 'problem_id': '6d3cfa40-26d2-41b1-b2b0-460228220e01', 'problem_data_id': '873bfcc8-1b54-4b6e-a8ca-76a4360067a4'}, 'INTEGER')

In [50]:
sampleset.truncate(5)

SampleSet(rec.array([([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False)],
          dtype=[('sample', '<f8', (10,)), ('energy', '<f8'), ('num_occurrences', '<i8'), ('is_satisfied', '?', (2,)), ('is_feasible', '?')]), Variables(['stock_GE', 'stock_GILD', 'stock_IBM', 'stock_MO', 'stock_PFE', 'stock_SFL', 'stock_T', 'stock_TSLA', 'stock_VZ', 'stock_XOM']), {'constraint_labels': ['budget_limitation', 'choose k stocks'], 'qpu_access_time': 69447, 'charge_time': 5000000, 'run_time': 5204678, 'problem_id': '6d3cfa40-26d2-41b1-b2b0-460228220e01', 'problem_data_id': '873bfcc8-1b54-4b6e-a8ca-76a4360067a4'}, 'INTEGER')

In [ ]:
for sample,/ energy, feasible in sampleset.data(fields=['sample', 'energy', 'is_feasible']):
    print(sample, energy, feasible)

{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)} -0.0017665541178559215 False
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)} -0.0017665541178559215 False
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)} -0.0017665541178559215 False
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)} -0.0017665541178559215 False
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)} -0.0017665541178559215 False
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)} -0.0017665541178559215 False
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)} -0.0017665541178559215 False
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)} -0.0017665541178559215 False
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)} -0.0017665541178559215 False
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)} -0.0017665541178559215 False
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)} -0.0017665541178559215 False
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)} -0.0017665541178559215 False
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True
{'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(1.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(0.0)} -0.001258040134328231 True

In [ ]:
# sampleset.record 구조 이해하기

print("=== sampleset.record 구조 ===")
print(f"record dtype: {sampleset.record.dtype}")
print(f"record shape: {sampleset.record.shape}")
print()

# record[0]은 첫 번째 샘플의 모든 정보
print("=== 첫 번째 샘플 (record[0])의 각 필드 ===")
first_record = sampleset.record[0]

# record의 구조는 다음과 같습니다:
# [0] = 'sample' (변수 값들, 배열)
# [1] = 'energy' (에너지 값)
# [2] = 'num_occurrences' (발생 횟수) ⭐ 이것이 1인 값!
# [3] = 'is_satisfied' (제약조건 만족 여부, 배열)
# [4] = 'is_feasible' (전체적으로 feasible한지)

print("인덱스별 의미:")
print(f"  [0] sample (변수 값들): {first_record[0]}")
print(f"  [1] energy (에너지): {first_record[1]}")
print(f"  [2] num_occurrences (발생 횟수): {first_record[2]} ⭐")
print(f"  [3] is_satisfied (제약조건 만족 여부): {first_record[3]}")
print(f"  [4] is_feasible (전체적으로 feasible): {first_record[4]}")
print()

# 이름으로 접근하는 방법 (더 명확함)
print("=== 이름으로 접근하는 방법 (권장) ===")
print(f"record[0]['sample']: {first_record['sample']}")
print(f"record[0]['energy']: {first_record['energy']}")
print(f"record[0]['num_occurrences']: {first_record['num_occurrences']}")
print(f"record[0]['is_satisfied']: {first_record['is_satisfied']}")
print(f"record[0]['is_feasible']: {first_record['is_feasible']}")
print()

# num_occurrences의 의미
print("=== num_occurrences의 의미 ===")
print("num_occurrences = 1은 이 샘플(해)이 샘플링 과정에서 1번 발견되었다는 의미입니다.")
print("값이 크면 그 해가 여러 번 발견되었다는 의미로, 더 안정적이고 신뢰할 수 있는 해일 수 있습니다.")
print()

# 올바른 접근 방법
print("=== 올바른 접근 방법 ===")
print("만약 feasible 값을 얻고 싶다면:")
print("  ❌ 잘못된 방법: sampleset.record[0][2]  # 이것은 num_occurrences")
print("  ✅ 올바른 방법: sampleset.record[0][4]  # 또는 sampleset.record[0]['is_feasible']")
print()
print("또는 더 간단하게:")
print("  sampleset.first.is_feasible")
print("  sampleset.first.num_occurrences")

In [51]:
sampleset.aggregate()

SampleSet(rec.array([([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 108, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], -0.00116939,   2, [ True, False], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655,  12, [False,  True], False)],
          dtype=[('sample', '<f8', (10,)), ('energy', '<f8'), ('num_occurrences', '<i8'), ('is_satisfied', '?', (2,)), ('is_feasible', '?')]), Variables(['stock_GE', 'stock_GILD', 'stock_IBM', 'stock_MO', 'stock_PFE', 'stock_SFL', 'stock_T', 'stock_TSLA', 'stock_VZ', 'stock_XOM']), {'constraint_labels': ['budget_limitation', 'choose k stocks'], 'qpu_access_time': 69447, 'charge_time': 5000000, 'run_time': 5204678, 'problem_id': '6d3cfa40-26d2-41b1-b2b0-460228220e01', 'problem_data_id': '873bfcc8-1b54-4b6e-a8ca-76a4360067a4'}, 'INTEGER')

In [57]:
sampleset.record

rec.array([([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], -0.00116939, 1, [ True, False], False),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 1, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 1, [False,  True], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], -0.00116939, 1, [ True, False], False)],
          dtype=[('sample', '<f8', (10,)), ('energy', '<f8'), ('num_occurrences', '<i8'), ('is_satisfied', '?', (2,)), ('is_feasible', '?')])

In [83]:
aggregate = sampleset.aggregate()
aggregate.record

rec.array([([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 108, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], -0.00116939,   2, [ True, False], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655,  12, [False,  True], False)],
          dtype=[('sample', '<f8', (10,)), ('energy', '<f8'), ('num_occurrences', '<i8'), ('is_satisfied', '?', (2,)), ('is_feasible', '?')])

In [84]:
holding_vector = aggregate.record[0][0]
energy = aggregate.record[0][1]
num_occurrences = aggregate.record[0][2]
constraints = aggregate.record[0][3]
feasible = aggregate.record[0][4]

In [86]:
holding_vectors = [record[0] for record in aggregate.record]
holding_vectors

[array([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.])]

In [90]:
df2 = pd.DataFrame(data=[record[0] for record in sampleset.record], columns=opt.tickers)
df2['energy'] = [record[1] for record in sampleset.record]
df2['num_occurrences'] = [record[2] for record in sampleset.record]
df2['constraints'] = [record[3] for record in sampleset.record]
df2['feasible'] = [record[4] for record in sampleset.record]
df2

,T,SFL,PFE,XOM,MO,VZ,IBM,TSLA,GILD,GE,energy,num_occurrences,constraints,feasible
0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,-0.001258,1,"[True, True]",True
1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,-0.001258,1,"[True, True]",True
2,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,-0.001258,1,"[True, True]",True
3,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,-0.001258,1,"[True, True]",True
4,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,-0.001258,1,"[True, True]",True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.001767,1,"[False, True]",False
118,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.001767,1,"[False, True]",False
119,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.001767,1,"[False, True]",False
120,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.001767,1,"[False, True]",False
121,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-0.001169,1,"[True, False]",False

In [91]:
df2.to_csv("record.csv", index=False)

In [87]:
df = pd.DataFrame(data=holding_vectors, columns=opt.tickers)
df['energy'] = [record[1] for record in aggregate.record]
df['num_occurrences'] = [record[2] for record in aggregate.record]
df['constraints'] = [record[3] for record in aggregate.record]
df['feasible'] = [record[4] for record in aggregate.record]
df

,T,SFL,PFE,XOM,MO,VZ,IBM,TSLA,GILD,GE,energy,num_occurrences,constraints,feasible
0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,-0.001258,108,"[True, True]",True
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-0.001169,2,"[True, False]",False
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.001767,12,"[False, True]",False

In [88]:
df.to_csv("aggregate.csv", index=False)

In [ ]:
df.aggregate()

In [93]:
aggregate

SampleSet(rec.array([([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], -0.00125804, 108, [ True,  True],  True),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], -0.00116939,   2, [ True, False], False),
           ([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655,  12, [False,  True], False)],
          dtype=[('sample', '<f8', (10,)), ('energy', '<f8'), ('num_occurrences', '<i8'), ('is_satisfied', '?', (2,)), ('is_feasible', '?')]), Variables(['stock_GE', 'stock_GILD', 'stock_IBM', 'stock_MO', 'stock_PFE', 'stock_SFL', 'stock_T', 'stock_TSLA', 'stock_VZ', 'stock_XOM']), {'constraint_labels': ['budget_limitation', 'choose k stocks'], 'qpu_access_time': 69447, 'charge_time': 5000000, 'run_time': 5204678, 'problem_id': '6d3cfa40-26d2-41b1-b2b0-460228220e01', 'problem_data_id': '873bfcc8-1b54-4b6e-a8ca-76a4360067a4'}, 'INTEGER')

In [92]:
aggregate.lowest()

SampleSet(rec.array([([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], -0.00176655, 12, [False,  True], False)],
          dtype=[('sample', '<f8', (10,)), ('energy', '<f8'), ('num_occurrences', '<i8'), ('is_satisfied', '?', (2,)), ('is_feasible', '?')]), Variables(['stock_GE', 'stock_GILD', 'stock_IBM', 'stock_MO', 'stock_PFE', 'stock_SFL', 'stock_T', 'stock_TSLA', 'stock_VZ', 'stock_XOM']), {'constraint_labels': ['budget_limitation', 'choose k stocks'], 'qpu_access_time': 69447, 'charge_time': 5000000, 'run_time': 5204678, 'problem_id': '6d3cfa40-26d2-41b1-b2b0-460228220e01', 'problem_data_id': '873bfcc8-1b54-4b6e-a8ca-76a4360067a4'}, 'INTEGER')

In [66]:
data_holding = {ticker: int(x) for ticker, x in zip(opt.tickers, holding_vector)}
data_holding

{'T': 0,
 'SFL': 0,
 'PFE': 0,
 'XOM': 0,
 'MO': 0,
 'VZ': 1,
 'IBM': 1,
 'TSLA': 0,
 'GILD': 0,
 'GE': 0}

In [ ]:
data

In [41]:
# 제약조건 검증
import numpy as np

# 첫 번째 샘플 가져오기
first_sample = sampleset.first
sample_dict = first_sample.sample

print("=== 제약조건 검증 ===")
print(f"샘플: {sample_dict}")
print()

# 1. 첫 번째 제약조건: 정확히 num_stocks_to_buy 개의 주식을 선택
selected_stocks = sum(sample_dict.values())
print(f"1. 'choose k stocks' 제약조건:")
print(f"   선택된 주식 수: {selected_stocks}")
print(f"   요구사항: {opt.num_stocks_to_buy}")
print(f"   만족 여부: {selected_stocks == opt.num_stocks_to_buy}")
print()

# 2. 두 번째 제약조건: 예산 제한
total_cost = sum(sample_dict[f'stock_{ticker}'] * opt.last_prices[i] 
                 for i, ticker in enumerate(opt.tickers))
print(f"2. 'budget_limitation' 제약조건:")
print(f"   총 비용: {total_cost:.2f}")
print(f"   예산: {opt.budget}")
print(f"   만족 여부: {total_cost <= opt.budget}")
print()

# 3. SampleSet이 보고하는 is_feasible과 is_satisfied 확인
print(f"3. SampleSet의 제약조건 검증 결과:")
print(f"   is_feasible: {first_sample.is_feasible}")
print(f"   is_satisfied: {first_sample.is_satisfied}")
print(f"   (is_satisfied는 각 제약조건별 만족 여부: {list(first_sample.is_satisfied)})")
print()

# 4. 선택된 주식 확인
print(f"4. 선택된 주식:")
for ticker in opt.tickers:
    if sample_dict[f'stock_{ticker}'] == 1:
        price = opt.last_prices[opt.tickers.index(ticker)]
        print(f"   - {ticker}: 가격 ${price:.2f}")
print()

# 5. CQM의 제약조건 정보 확인
print(f"5. CQM 제약조건 정보:")
for constraint_name in cqm.constraints:
    constraint = cqm.constraints[constraint_name]
    print(f"   - {constraint_name}: {constraint}")

=== 제약조건 검증 ===
샘플: {'stock_GE': np.float64(0.0), 'stock_GILD': np.float64(0.0), 'stock_IBM': np.float64(0.0), 'stock_MO': np.float64(0.0), 'stock_PFE': np.float64(0.0), 'stock_SFL': np.float64(1.0), 'stock_T': np.float64(0.0), 'stock_TSLA': np.float64(0.0), 'stock_VZ': np.float64(0.0), 'stock_XOM': np.float64(1.0)}

1. 'choose k stocks' 제약조건:
   선택된 주식 수: 2.0
   요구사항: 2
   만족 여부: True

2. 'budget_limitation' 제약조건:
   총 비용: 45.31
   예산: 40.0
   만족 여부: False

3. SampleSet의 제약조건 검증 결과:
   is_feasible: False
   is_satisfied: [False  True]
   (is_satisfied는 각 제약조건별 만족 여부: [np.False_, np.True_])

4. 선택된 주식:
   - SFL: 가격 $5.95
   - XOM: 가격 $39.35

5. CQM 제약조건 정보:
   - choose k stocks: stock_T + stock_SFL + stock_PFE + stock_XOM + stock_MO + stock_VZ + stock_IBM + stock_TSLA + stock_GILD + stock_GE == 2.0
   - budget_limitation: 27.286*stock_T + 5.9513*stock_SFL + 35.735*stock_PFE + 39.354*stock_XOM + 38.893*stock_MO + 56.873*stock_VZ + 121.45*stock_IBM + 705.67*stock_TSLA + 56.44*stock_GILD + 86.272*stock_GE <= 40.0

In [32]:
sampleset.first.is_satisfied

array([False,  True])

In [ ]:
# SampleSet의 유용한 속성과 메소드

# 1. .first - 가장 낮은 에너지를 가진 첫 번째 샘플
print("=== 1. First Sample (Lowest Energy) ===")
first_sample = sampleset.first
print(f"Sample: {first_sample.sample}")
print(f"Energy: {first_sample.energy}")
print(f"Number of occurrences: {first_sample.num_occurrences}")
print(f"Is feasible: {first_sample.is_feasible}")
print(f"Is satisfied: {first_sample.is_satisfied}")
print()

# 2. .data() - 샘플 데이터를 반복 가능한 형태로 반환
print("=== 2. Data Iterator ===")
print("First 3 samples:")
for i, record in enumerate(sampleset.data()):
    if i >= 3:
        break
    print(f"  Sample {i+1}: Energy={record.energy:.6f}, Feasible={record.is_feasible}")
print()

# 3. .lowest() - 가장 낮은 에너지를 가진 샘플들만 반환
print("=== 3. Lowest Energy Samples ===")
lowest_samples = sampleset.lowest()
print(f"Number of lowest energy samples: {len(lowest_samples)}")
print(f"Lowest energy: {lowest_samples.first.energy}")
print()

# 4. .filter() - 조건에 맞는 샘플만 필터링
print("=== 4. Filter Feasible Samples ===")
feasible_samples = sampleset.filter(lambda s: s.is_feasible)
print(f"Number of feasible samples: {len(feasible_samples)}")
if len(feasible_samples) > 0:
    print(f"Best feasible energy: {feasible_samples.first.energy}")
print()

# 5. .variables - 변수 이름 리스트
print("=== 5. Variables ===")
print(f"Variable names: {list(sampleset.variables)}")
print()

# 6. .info - 메타데이터 (QPU 접근 시간, 실행 시간 등)
print("=== 6. Info (Metadata) ===")
print(f"QPU access time: {sampleset.info.get('qpu_access_time', 'N/A')} μs")
print(f"Run time: {sampleset.info.get('run_time', 'N/A')} μs")
print(f"Problem ID: {sampleset.info.get('problem_id', 'N/A')}")
print()

# 7. .record - 구조화된 배열 형태의 데이터
print("=== 7. Record Array ===")
print(f"Total number of samples: {len(sampleset.record)}")
print(f"Record dtype: {sampleset.record.dtype}")
print(f"First record energy: {sampleset.record[0]['energy']}")
print()

# 8. .aggregate() - 중복 샘플 집계
print("=== 8. Aggregate Samples ===")
aggregated = sampleset.aggregate()
print(f"Unique samples after aggregation: {len(aggregated)}")
print()

# 9. .truncate() - 샘플 수 제한
print("=== 9. Truncate to Top 5 ===")
top5 = sampleset.truncate(5)
print(f"Top 5 samples:")
for i, record in enumerate(top5.data()):
    print(f"  {i+1}. Energy={record.energy:.6f}, Feasible={record.is_feasible}")
print()

# 10. 특정 필드만 추출
print("=== 10. Extract Specific Fields ===")
for sample, energy, feasible in sampleset.data(fields=['sample', 'energy', 'is_feasible']):
    if feasible:
        print(f"Feasible solution found!")
        print(f"  Energy: {energy:.6f}")
        print(f"  Sample: {sample}")
        break

In [ ]:
def process_sampleset(sampleset, stockcodes):
    """Read in sampleset returned from sample_cqm command and display solution."""

    # Find the first feasible solution
    first_run = True
    feasible = False
    for sample, feas in sampleset.data(fields=['sample','is_feasible']):
        if first_run:
            best_sample = sample
        if feas:
            best_sample = sample
            feasible = True
            break

    # Print the solution as which stocks to buy
    print("Solution:\n")
    if not feasible:
        print("No feasible solution found.\n")
    else:
        print("Best feasible solution found:")
        for stk in stockcodes:
            if best_sample[f's_{stk}'] == 1:
                print(stk)
    print("\n")

In [ ]:
# 더 긴 시간으로 샘플링하여 제약조건을 만족하는 해 찾기
print("=== 더 긴 시간으로 샘플링 (time_limit=10초) ===")

# time_limit을 늘려서 더 나은 해를 찾기
sampleset_longer = opt.sample_cqm(time_limit=10.0)

# feasible한 샘플 필터링
feasible_samples = sampleset_longer.filter(lambda s: s.is_feasible)

print(f"전체 샘플 수: {len(sampleset_longer)}")
print(f"Feasible 샘플 수: {len(feasible_samples)}")
print()

if len(feasible_samples) > 0:
    best_feasible = feasible_samples.first
    print("가장 좋은 feasible 해:")
    print(f"  샘플: {best_feasible.sample}")
    print(f"  에너지: {best_feasible.energy:.6f}")
    print(f"  선택된 주식:")
    
    sample_dict = best_feasible.sample
    total_cost = 0
    for ticker in opt.tickers:
        if sample_dict[f'stock_{ticker}'] == 1:
            price = opt.last_prices[opt.tickers.index(ticker)]
            total_cost += price
            print(f"    - {ticker}: 가격 ${price:.2f}")
    print(f"  총 비용: ${total_cost:.2f} (예산: ${opt.budget:.2f})")
else:
    print("⚠️ Feasible한 해를 찾지 못했습니다.")
    print("예산이 너무 낮거나 문제가 해결 불가능할 수 있습니다.")
    print()
    print("가능한 해결 방법:")
    print("1. time_limit을 더 늘리기 (예: 20초, 30초)")
    print("2. 예산을 늘리기")
    print("3. 선택할 주식 수를 줄이기")

## 제약조건을 "더 강하게" 만드는 방법

CQM(Constrained Quadratic Model)에서 제약조건은 이미 **하드 제약(hard constraint)**입니다. 즉, 제약조건을 위반하는 해는 절대 허용되지 않습니다.

하지만 샘플러가 제약조건을 만족하는 해를 찾지 못하는 경우가 있습니다. 이는 다음 이유 때문일 수 있습니다:

1. **샘플링 시간이 부족**: 더 긴 시간을 주면 더 나은 해를 찾을 수 있습니다.
2. **문제가 해결 불가능**: 예산이 너무 낮아서 제약조건을 만족하는 해가 없을 수 있습니다.
3. **샘플러의 한계**: 양자 하이브리드 샘플러도 완벽하지 않을 수 있습니다.

### 해결 방법:

1. **`time_limit` 파라미터 증가**: `opt.sample_cqm(time_limit=20.0)` 같이 시간을 늘립니다.
2. **예산 조정**: 예산이 너무 낮으면 해가 없을 수 있습니다.
3. **제약조건 재검토**: 제약조건이 논리적으로 올바른지 확인합니다.

**참고**: CQM에서는 제약조건의 "강도"를 조절할 수 없습니다. 제약조건은 만족되거나 위반되거나 둘 중 하나입니다.

In [ ]:
# 원래 코드에서 사용된 기본 time_limit 확인
# (time_limit을 지정하지 않으면 샘플러가 자동으로 결정)

print("=== 원래 코드의 동작 확인 ===")
print("원래 코드에서는 time_limit을 지정하지 않았습니다.")
print("LeapHybridCQMSampler가 자동으로 시간을 결정합니다.")
print()

# 원래 방식으로 샘플링 (time_limit 없음)
sampler = LeapHybridCQMSampler()
sampleset_original = sampler.sample_cqm(cqm)  # time_limit 없음

print(f"자동 결정된 샘플링 결과:")
print(f"  전체 샘플 수: {len(sampleset_original)}")
print(f"  Feasible 샘플 수: {len(sampleset_original.filter(lambda s: s.is_feasible))}")
print(f"  실행 시간: {sampleset_original.info.get('run_time', 'N/A')} μs")
print()

# time_limit을 명시적으로 지정한 경우와 비교
print("=== time_limit=5.0으로 명시적으로 지정한 경우 ===")
sampleset_explicit = sampler.sample_cqm(cqm, time_limit=5.0)
print(f"  전체 샘플 수: {len(sampleset_explicit)}")
print(f"  Feasible 샘플 수: {len(sampleset_explicit.filter(lambda s: s.is_feasible))}")
print(f"  실행 시간: {sampleset_explicit.info.get('run_time', 'N/A')} μs")

In [3]:
si.tickers

['T', 'SFL', 'PFE', 'XOM', 'MO', 'VZ', 'IBM', 'TSLA', 'GILD', 'GE']

In [4]:
si.df_covariances

,T,SFL,PFE,XOM,MO,VZ,IBM,TSLA,GILD,GE
T,0.000290,0.000198,0.000143,0.000216,0.000167,0.000145,0.000200,0.000135,0.000122,0.000245
SFL,0.000198,0.000812,0.000123,0.000384,0.000219,0.000087,0.000236,0.000395,0.000081,0.000389
PFE,0.000143,0.000123,0.000272,0.000156,0.000127,0.000107,0.000173,0.000122,0.000144,0.000184
XOM,0.000216,0.000384,0.000156,0.000482,0.000192,0.000117,0.000262,0.000268,0.000121,0.000392
MO,0.000167,0.000219,0.000127,0.000192,0.000337,0.000113,0.000158,0.000158,0.000094,0.000233
VZ,0.000145,0.000087,0.000107,0.000117,0.000113,0.000167,0.000126,0.000072,0.000094,0.000126
IBM,0.000200,0.000236,0.000173,0.000262,0.000158,0.000126,0.000366,0.000235,0.000149,0.000324
TSLA,0.000135,0.000395,0.000122,0.000268,0.000158,0.000072,0.000235,0.001861,0.000190,0.000332
GILD,0.000122,0.000081,0.000144,0.000121,0.000094,0.000094,0.000149,0.000190,0.000344,0.000122
GE,0.000245,0.000389,0.000184,0.000392,0.000233,0.000126,0.000324,0.000332,0.000122,0.000964

In [5]:
si.last_prices

array([ 27.286 ,   5.9513,  35.735 ,  39.354 ,  38.893 ,  56.873 ,
       121.45  , 705.67  ,  56.44  ,  86.272 ])

In [6]:
si.average_returns

[0.0002869008207864618,
 0.0011693903365152462,
 -2.5777490342813673e-05,
 0.000981218376138591,
 0.0006163644638600048,
 -0.0002123319117285607,
 0.0002618752921641446,
 -0.0022521076250798227,
 0.00034624495391212724,
 0.001105261292478064]

In [9]:
# si.get_covariance_column('T')
si.get_covariance_component('T', 'T')

np.float64(0.00029040856718167253)

In [6]:
info.variance

[[0.00029040856718167253,
  0.00019825102297347684,
  0.00014316854380358514,
  0.00021588477534911272,
  0.00016718262217650556,
  0.0001450250666800619,
  0.00020014333968182028,
  0.00013504932902227813,
  0.00012230972955248223,
  0.00024519130634880463],
 [0.00019825102297347684,
  0.0008120686172848818,
  0.00012288727756433823,
  0.0003840545947979156,
  0.0002188867175407716,
  8.69954997699092e-05,
  0.00023552118181180333,
  0.0003954865554431437,
  8.119484922285677e-05,
  0.00038923712879381444],
 [0.00014316854380358514,
  0.00012288727756433823,
  0.00027241861370539246,
  0.00015570275547213878,
  0.00012716263562149288,
  0.00010741763649840176,
  0.00017349340359509437,
  0.00012195768833301645,
  0.00014375911999241464,
  0.00018389908563358075],
 [0.00021588477534911272,
  0.0003840545947979156,
  0.00015570275547213878,
  0.0004819772749102193,
  0.00019200269683075945,
  0.00011733886215995178,
  0.00026196576538175436,
  0.00026763098591531123,
  0.00012109209434059107,
  0.00039224393524215875],
 [0.00016718262217650556,
  0.0002188867175407716,
  0.00012716263562149288,
  0.00019200269683075945,
  0.000337049209044536,
  0.0001132267509907128,
  0.00015788101905710026,
  0.0001578475997176579,
  9.407488417742071e-05,
  0.0002327062462905184],
 [0.0001450250666800619,
  8.69954997699092e-05,
  0.00010741763649840176,
  0.00011733886215995178,
  0.0001132267509907128,
  0.0001671041137717056,
  0.00012599277966820948,
  7.197300290258289e-05,
  9.448619613769027e-05,
  0.000126485493600361],
 [0.00020014333968182028,
  0.00023552118181180333,
  0.00017349340359509437,
  0.00026196576538175436,
  0.00015788101905710026,
  0.00012599277966820948,
  0.000366028444077389,
  0.0002349457413459874,
  0.00014945983526337074,
  0.0003242134255977041],
 [0.00013504932902227813,
  0.0003954865554431437,
  0.00012195768833301645,
  0.00026763098591531123,
  0.0001578475997176579,
  7.197300290258289e-05,
  0.0002349457413459874,
  0.001860619607358314,
  0.0001903125151555422,
  0.00033157428306385014],
 [0.00012230972955248223,
  8.119484922285677e-05,
  0.00014375911999241464,
  0.00012109209434059107,
  9.407488417742071e-05,
  9.448619613769027e-05,
  0.00014945983526337074,
  0.0001903125151555422,
  0.00034379237492702914,
  0.00012221542936312262],
 [0.00024519130634880463,
  0.00038923712879381444,
  0.00018389908563358075,
  0.00039224393524215875,
  0.0002327062462905184,
  0.000126485493600361,
  0.0003242134255977041,
  0.00033157428306385014,
  0.00012221542936312262,
  0.0009637736655878987]]

In [7]:
price, returns, variance = get_stock_info()

In [8]:
price

array([ 27.286 ,   5.9513,  35.735 ,  39.354 ,  38.893 ,  56.873 ,
       121.45  , 705.67  ,  56.44  ,  86.272 ])

In [9]:
returns

[0.0002869008207864618,
 0.0011693903365152462,
 -2.5777490342813673e-05,
 0.000981218376138591,
 0.0006163644638600048,
 -0.0002123319117285607,
 0.0002618752921641446,
 -0.0022521076250798227,
 0.00034624495391212724,
 0.001105261292478064]

In [13]:
variance

[[0.00029040856718167253,
  0.00019825102297347684,
  0.00014316854380358514,
  0.00021588477534911272,
  0.00016718262217650556,
  0.0001450250666800619,
  0.00020014333968182028,
  0.00013504932902227813,
  0.00012230972955248223,
  0.00024519130634880463],
 [0.00019825102297347684,
  0.0008120686172848818,
  0.00012288727756433823,
  0.0003840545947979156,
  0.0002188867175407716,
  8.69954997699092e-05,
  0.00023552118181180333,
  0.0003954865554431437,
  8.119484922285677e-05,
  0.00038923712879381444],
 [0.00014316854380358514,
  0.00012288727756433823,
  0.00027241861370539246,
  0.00015570275547213878,
  0.00012716263562149288,
  0.00010741763649840176,
  0.00017349340359509437,
  0.00012195768833301645,
  0.00014375911999241464,
  0.00018389908563358075],
 [0.00021588477534911272,
  0.0003840545947979156,
  0.00015570275547213878,
  0.0004819772749102193,
  0.00019200269683075945,
  0.00011733886215995178,
  0.00026196576538175436,
  0.00026763098591531123,
  0.00012109209434059107,
  0.00039224393524215875],
 [0.00016718262217650556,
  0.0002188867175407716,
  0.00012716263562149288,
  0.00019200269683075945,
  0.000337049209044536,
  0.0001132267509907128,
  0.00015788101905710026,
  0.0001578475997176579,
  9.407488417742071e-05,
  0.0002327062462905184],
 [0.0001450250666800619,
  8.69954997699092e-05,
  0.00010741763649840176,
  0.00011733886215995178,
  0.0001132267509907128,
  0.0001671041137717056,
  0.00012599277966820948,
  7.197300290258289e-05,
  9.448619613769027e-05,
  0.000126485493600361],
 [0.00020014333968182028,
  0.00023552118181180333,
  0.00017349340359509437,
  0.00026196576538175436,
  0.00015788101905710026,
  0.00012599277966820948,
  0.000366028444077389,
  0.0002349457413459874,
  0.00014945983526337074,
  0.0003242134255977041],
 [0.00013504932902227813,
  0.0003954865554431437,
  0.00012195768833301645,
  0.00026763098591531123,
  0.0001578475997176579,
  7.197300290258289e-05,
  0.0002349457413459874,
  0.001860619607358314,
  0.0001903125151555422,
  0.00033157428306385014],
 [0.00012230972955248223,
  8.119484922285677e-05,
  0.00014375911999241464,
  0.00012109209434059107,
  9.407488417742071e-05,
  9.448619613769027e-05,
  0.00014945983526337074,
  0.0001903125151555422,
  0.00034379237492702914,
  0.00012221542936312262],
 [0.00024519130634880463,
  0.00038923712879381444,
  0.00018389908563358075,
  0.00039224393524215875,
  0.0002327062462905184,
  0.000126485493600361,
  0.0003242134255977041,
  0.00033157428306385014,
  0.00012221542936312262,
  0.0009637736655878987]]

In [15]:
df_monthreturn = pd.read_csv("data/monthly_returns.csv", index_col='Date')
df_monthreturn

,T,SFL,PFE,XOM,MO,VZ,IBM,TSLA,GILD,GE
Date,,,,,,,,,,
2020-12-30,-0.009419,-0.025473,-0.001903,0.009224,-0.006325,-0.010374,-0.012268,-0.015432,-0.027622,-0.008346
2020-12-29,0.001776,-0.009794,0.008411,-0.007931,-0.000233,0.011513,-0.004335,-0.041438,0.003170,-0.014027
2020-12-28,0.000332,-0.004963,-0.006172,0.011395,0.018402,0.002898,0.008205,-0.003454,0.001053,0.007587
2020-12-24,0.004910,0.024867,0.012198,-0.003363,0.005794,-0.002382,-0.000997,-0.002893,0.003175,0.000941
2020-12-23,0.002094,-0.021019,0.004588,0.004054,0.006948,0.002037,-0.006318,-0.023860,0.005426,0.019748
...,...,...,...,...,...,...,...,...,...,...
2018-01-08,0.006976,0.006560,0.001012,0.004268,0.010653,0.003720,-0.002042,0.008151,-0.047389,-0.015118
2018-01-05,-0.002884,0.013129,0.011312,-0.004476,0.001290,0.001707,-0.005993,-0.058946,0.001609,0.014213
2018-01-04,-0.003723,0.000000,-0.001937,0.000840,-0.002834,0.002287,-0.004926,-0.006191,-0.008278,-0.000561
2018-01-03,-0.009176,0.006526,-0.002191,-0.001407,0.003986,-0.003266,-0.019877,0.008359,0.010044,-0.020401
2018-01-02,0.023673,0.003149,-0.007342,-0.019291,0.003658,0.021009,-0.026689,0.010339,-0.007277,-0.009590

In [16]:
ave_monthly_returns = df_monthreturn.mean(axis=0)
returns = list(ave_monthly_returns)

# Compute the variance from the monthly returns
variance = df_monthreturn.cov().values.tolist()

In [17]:
ave_monthly_returns

T       0.000287
SFL     0.001169
PFE    -0.000026
XOM     0.000981
MO      0.000616
VZ     -0.000212
IBM     0.000262
TSLA   -0.002252
GILD    0.000346
GE      0.001105
dtype: float64

In [18]:
returns

[0.0002869008207864618,
 0.0011693903365152462,
 -2.5777490342813673e-05,
 0.000981218376138591,
 0.0006163644638600048,
 -0.0002123319117285607,
 0.0002618752921641446,
 -0.0022521076250798227,
 0.00034624495391212724,
 0.001105261292478064]

In [23]:
df_monthreturn.cov()

,T,SFL,PFE,XOM,MO,VZ,IBM,TSLA,GILD,GE
T,0.000290,0.000198,0.000143,0.000216,0.000167,0.000145,0.000200,0.000135,0.000122,0.000245
SFL,0.000198,0.000812,0.000123,0.000384,0.000219,0.000087,0.000236,0.000395,0.000081,0.000389
PFE,0.000143,0.000123,0.000272,0.000156,0.000127,0.000107,0.000173,0.000122,0.000144,0.000184
XOM,0.000216,0.000384,0.000156,0.000482,0.000192,0.000117,0.000262,0.000268,0.000121,0.000392
MO,0.000167,0.000219,0.000127,0.000192,0.000337,0.000113,0.000158,0.000158,0.000094,0.000233
VZ,0.000145,0.000087,0.000107,0.000117,0.000113,0.000167,0.000126,0.000072,0.000094,0.000126
IBM,0.000200,0.000236,0.000173,0.000262,0.000158,0.000126,0.000366,0.000235,0.000149,0.000324
TSLA,0.000135,0.000395,0.000122,0.000268,0.000158,0.000072,0.000235,0.001861,0.000190,0.000332
GILD,0.000122,0.000081,0.000144,0.000121,0.000094,0.000094,0.000149,0.000190,0.000344,0.000122
GE,0.000245,0.000389,0.000184,0.000392,0.000233,0.000126,0.000324,0.000332,0.000122,0.000964

In [24]:
df_monthreturn.cov().values.tolist()[0]

[0.00029040856718167253,
 0.00019825102297347684,
 0.00014316854380358514,
 0.00021588477534911272,
 0.00016718262217650556,
 0.0001450250666800619,
 0.00020014333968182028,
 0.00013504932902227813,
 0.00012230972955248223,
 0.00024519130634880463]